#!/usr/bin/env python3
r"""Generate LaTeX dataset statistics for the thesis document.

Reads the repository-versioned per-discipline season indices (one row per season:
``n_flights``, ``n_with_igc``, ``n_downloaded``):

* ``data/paragliders/seasons_index.csv``  -- paraglider CFD (parapente.ffvl.fr);
* ``data/hang_gliders/seasons_index.csv`` -- hang-glider CFD (delta.ffvl.fr).

and writes the auto-generated LaTeX files included by ``thesis/main.tex``:

* ``stats.tex`` -- ``\newcommand`` macros with the headline numbers, per discipline
  (``\StatPara*`` / ``\StatHang*``) and combined (``\StatTotal*``), plus the date;
* ``seasons_table_para.tex`` -- per-season ``longtable`` (paragliders);
* ``seasons_table_hang.tex`` -- per-season ``longtable`` (hang gliders).

The script is deterministic and has no third-party dependencies, so it can run both in a
git hook and in CI. It reads only the committed CSVs (never the external disk), so the
numbers always match what is in the repository. Those committed CSVs are the offline
snapshot of the canonical SSD indices; ``refresh_seasons_index.py`` re-copies them from
the SSD (when mounted) so the snapshot does not drift.
"""

from __future__ import annotations

import csv
from dataclasses import dataclass
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT_DIR = ROOT / "thesis" / "generated"

_AUTOGEN = "% AUTO-GENERATED by scripts/reporting/generate_stats.py -- DO NOT EDIT.\n"


@dataclass(frozen=True)
class Dataset:
    """One glider discipline: its LaTeX macro prefix, CSV, and table metadata."""

    prefix: str  # LaTeX macro infix, e.g. "Para" -> \StatParaTotalFlights
    slug: str  # output file suffix, e.g. "para" -> seasons_table_para.tex
    csv_path: Path
    caption: str  # longtable caption (source is spelled out per discipline)


DATASETS = [
    Dataset(
        prefix="Para",
        slug="para",
        csv_path=ROOT / "data" / "paragliders" / "seasons_index.csv",
        caption=(
            "FFVL CFD \\emph{paraglider} flights per season "
            "(\\texttt{parapente.ffvl.fr}): total declared, with a GPS track, and "
            "downloaded. \\impldetails{impl:coverage}"
        ),
    ),
    Dataset(
        prefix="Hang",
        slug="hang",
        csv_path=ROOT / "data" / "hang_gliders" / "seasons_index.csv",
        caption=(
            "FFVL CFD \\emph{hang-glider} flights per season "
            "(\\texttt{delta.ffvl.fr}): total declared, with a GPS track, and "
            "downloaded. \\impldetails{impl:coverage}"
        ),
    ),
]


def _season_label(raw: str) -> str:
    """Turn ``"1999-2000"`` into the LaTeX en-dash form ``"1999--2000"``."""
    return raw.replace("-", "--")


def _pct(part: int, whole: int) -> float:
    """Percentage ``part/whole`` (one decimal), ``0.0`` if ``whole`` is zero."""
    return round(100.0 * part / whole, 1) if whole else 0.0


def _read_rows(csv_path: Path) -> list[dict[str, str]]:
    """Read and return the rows of a ``seasons_index.csv``."""
    if not csv_path.is_file():
        raise SystemExit(
            f"Missing {csv_path}. With the SSD mounted, refresh the committed snapshot "
            "with: uv run python scripts/reporting/refresh_seasons_index.py"
        )
    with csv_path.open(newline="", encoding="utf-8") as fh:
        return list(csv.DictReader(fh))


def _totals(rows: list[dict[str, str]]) -> tuple[int, int, int]:
    """Sum ``(n_flights, n_with_igc, n_downloaded)`` over the seasons."""
    n_flights = sum(int(r["n_flights"]) for r in rows)
    n_with_igc = sum(int(r["n_with_igc"]) for r in rows)
    n_downloaded = sum(int(r["n_downloaded"]) for r in rows)
    return n_flights, n_with_igc, n_downloaded


def _macros_for(ds: Dataset, rows: list[dict[str, str]]) -> list[str]:
    r"""Per-discipline ``\newcommand`` macros (prefix ``\Stat<prefix>...``)."""
    n_flights, n_with_igc, n_downloaded = _totals(rows)
    p = ds.prefix
    return [
        f"\\newcommand{{\\Stat{p}NumSeasons}}{{{len(rows)}}}\n",
        f"\\newcommand{{\\Stat{p}SeasonFirst}}{{{_season_label(rows[0]['season'])}}}\n",
        f"\\newcommand{{\\Stat{p}SeasonLast}}{{{_season_label(rows[-1]['season'])}}}\n",
        f"\\newcommand{{\\Stat{p}TotalFlights}}{{{n_flights}}}\n",
        f"\\newcommand{{\\Stat{p}WithIgc}}{{{n_with_igc}}}\n",
        f"\\newcommand{{\\Stat{p}Downloaded}}{{{n_downloaded}}}\n",
        f"\\newcommand{{\\Stat{p}PctWithIgc}}{{{_pct(n_with_igc, n_flights)}}}\n",
        f"\\newcommand{{\\Stat{p}PctDownloaded}}{{{_pct(n_downloaded, n_with_igc)}}}\n",
    ]


def _write_macros(datasets: list[tuple[Dataset, list[dict[str, str]]]]) -> None:
    """Write per-discipline and combined headline macros to ``stats.tex``."""
    lines = [
        _AUTOGEN,
        f"\\newcommand{{\\StatGenerated}}{{{date.today().isoformat()}}}\n",
    ]
    grand = [0, 0, 0]
    for ds, rows in datasets:
        lines.extend(_macros_for(ds, rows))
        for i, v in enumerate(_totals(rows)):
            grand[i] += v
    lines.extend(
        [
            f"\\newcommand{{\\StatTotalFlights}}{{{grand[0]}}}\n",
            f"\\newcommand{{\\StatTotalWithIgc}}{{{grand[1]}}}\n",
            f"\\newcommand{{\\StatTotalDownloaded}}{{{grand[2]}}}\n",
        ]
    )
    (OUT_DIR / "stats.tex").write_text("".join(lines), encoding="utf-8")


def _write_table(ds: Dataset, rows: list[dict[str, str]]) -> None:
    """Write one per-season ``longtable`` to ``seasons_table_<slug>.tex``."""
    out = [
        _AUTOGEN,
        "\\begin{longtable}{l S S S S}\n",
        f"\\caption{{{ds.caption}}}\\label{{tab:seasons-{ds.slug}}}\\\\\n",
        "\\toprule\n",
        "Season & {Flights} & {With GPS} & {Downloaded} & {Coverage (\\%)} \\\\\n",
        "\\midrule\n\\endfirsthead\n",
        "\\toprule\n",
        "Season & {Flights} & {With GPS} & {Downloaded} & {Coverage (\\%)} \\\\\n",
        "\\midrule\n\\endhead\n",
        "\\midrule\n\\endfoot\n",
        "\\bottomrule\n\\endlastfoot\n",
    ]
    tot_f = tot_i = tot_d = 0
    for r in rows:
        n_f = int(r["n_flights"])
        n_i = int(r["n_with_igc"])
        n_d = int(r["n_downloaded"])
        tot_f += n_f
        tot_i += n_i
        tot_d += n_d
        out.append(
            f"{_season_label(r['season'])} & {n_f} & {n_i} & {n_d} & "
            f"{_pct(n_d, n_i)} \\\\\n"
        )
    out.append("\\midrule\n")
    out.append(
        f"\\textbf{{Total}} & {tot_f} & {tot_i} & {tot_d} & {_pct(tot_d, tot_i)} \\\\\n"
    )
    out.append("\\end{longtable}\n")
    out_path = OUT_DIR / f"seasons_table_{ds.slug}.tex"
    out_path.write_text("".join(out), encoding="utf-8")


def main() -> int:
    """Generate the macros and the two per-season tables; return an exit code."""
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    loaded = [(ds, _read_rows(ds.csv_path)) for ds in DATASETS]
    _write_macros(loaded)
    for ds, rows in loaded:
        _write_table(ds, rows)
    summary = ", ".join(f"{ds.slug}={len(rows)}" for ds, rows in loaded)
    print(f"Wrote stats.tex and seasons_table_{{para,hang}}.tex (seasons: {summary}).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
