#!/usr/bin/env python3
r"""Trace every generated number, table and figure in the thesis back to the code.

The thesis quotes its numbers through macros and draws its figures from files, and none
of them are typed by hand: each is written into ``thesis/generated/`` by a script that
reads the archive. That is the right arrangement, and it has one cost. The chain from a
figure on a page to the estimator behind it is invisible from both ends: a reader asking
where a number comes from has to grep, and a grep answers for a macro whose name they
already know rather than for the sentence they were reading.

This writes that answer out as a page. For every generated file and every macro family:
which script produced it, which step of ``regenerate.sh`` runs that script, and which
sections of the thesis use it.

**It is generated rather than written**, for the same reason the numbers are. A
provenance table maintained by hand is correct on the day it is written and wrong at the
first rename, in the way that is hardest to notice, since nothing fails. Everything here
is read from the repository at run time:

* which script writes an artefact, from the ``OUT_* = ROOT / "thesis" / "generated" /
  "..."`` assignment in its source;
* which macros a generated file defines, from its ``\newcommand`` lines;
* which script a generated file claims as its author, from its ``% Generated by`` line;
* where the thesis uses a macro or a figure, from the section sources;
* which step runs a script, from ``regenerate.sh`` and the pre-commit hook.

``--check`` turns the same scan into a test: it fails if a generated file carries no
provenance header, or if a header names a different script from the one whose source
builds that path. Whether the thesis quotes a macro that nothing defines is the
neighbouring question, and ``check_generated_macros.py`` answers it; both run in the
chain, because the two failures look alike and have different causes.

Usage::

    python scripts/reporting/generate_provenance.py [--check]
"""

from __future__ import annotations

import argparse
import re
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
THESIS = ROOT / "thesis"
GENERATED = THESIS / "generated"
OUT_MD = ROOT / "docs" / "guide" / "provenance.md"

# The thesis sources that may quote a macro or include a figure.
SOURCES = sorted(
    [
        *THESIS.glob("sections/*.tex"),
        *THESIS.glob("appendices/**/*.tex"),
        THESIS / "main.tex",
    ]
)

# A script names what it writes by assigning the path to an OUT_* constant, which is how
# this repo has always spelled an output. Requiring the name as well as the path is what
# separates writing from reading: audit_msd_report.py also names msd_curve.csv, as
# CURVE_CSV, because it consumes what generate_msd_figure.py produced. Matching a bare
# filename would read a docstring mention as authorship -- three scripts name
# altitude_noise.pdf in prose and one writes it.
_WRITES = re.compile(
    r'OUT\w*\s*=\s*ROOT\s*/\s*"thesis"\s*/\s*"generated"\s*/\s*"([^"]+)"'
)
_HEADER = re.compile(r"^%\s*Generated by\s+(\S+\.py)", re.M)
_MACRO = re.compile(r"\\newcommand\{\\(\w+)\}")
_FIGURE = re.compile(r"\\includegraphics(?:\[[^\]]*\])?\{generated/([^}]+)\}")
_STEP = re.compile(r'^step "(\d+)/\d+\s+([^"]*)"|^"\$PY"\s+(\S+\.py)', re.M)


def writers() -> dict[str, str]:
    """Generated filename -> the script whose source declares it as an output."""
    found: dict[str, str] = {}
    for script in sorted(ROOT.glob("scripts/**/*.py")):
        rel = script.relative_to(ROOT).as_posix()
        for name in _WRITES.findall(script.read_text()):
            found.setdefault(name, rel)
    return found


def steps() -> dict[str, int]:
    """Script -> its step number in ``regenerate.sh``."""
    out: dict[str, int] = {}
    pending: int | None = None
    text = (ROOT / "scripts" / "regenerate.sh").read_text()
    for number, _label, script in _STEP.findall(text):
        if number:
            pending = int(number)
        elif pending is not None:
            out.setdefault(script, pending)
    return out


def hook_scripts() -> set[str]:
    """The scripts the pre-commit hook runs, which ``regenerate.sh`` does not."""
    text = (ROOT / ".githooks" / "pre-commit").read_text()
    return set(re.findall(r"scripts/[\w/]+\.py", text))


def defined_macros() -> dict[str, str]:
    """Macro name -> the generated file that defines it."""
    out: dict[str, str] = {}
    for path in sorted(GENERATED.glob("*.tex")):
        for name in _MACRO.findall(path.read_text()):
            out[name] = path.name
    return out


def used_in(defined: set[str]) -> tuple[dict[str, set[str]], dict[str, set[str]]]:
    r"""``(macros, figures)``, each mapping a name to the thesis files that use it.

    Every control sequence in the sources is collected and intersected with the names
    the generators define, rather than filtered by an expected prefix. A family added
    under a new prefix is picked up with no change here, and ``\DataCascadeParaRows``
    -- which matches no ``Stat``/``Preproc`` convention, and is quoted in Ch. 2 -- is
    not reported missing.
    """
    macros: dict[str, set[str]] = defaultdict(set)
    figures: dict[str, set[str]] = defaultdict(set)
    for source in SOURCES:
        text = source.read_text()
        label = source.relative_to(THESIS).as_posix()
        for name in set(re.findall(r"\\(\w+)", text)) & defined:
            macros[name].add(label)
        for figure in _FIGURE.findall(text):
            figures[figure].add(label)
    return macros, figures


def collect() -> tuple[dict, dict, list[str]]:
    """``(artefacts, macros, problems)``, from one pass over the repository."""
    produced_by = writers()
    step_of = steps()
    by_hook = hook_scripts()
    defines = defined_macros()
    used, figures = used_in(set(defines))
    problems: list[str] = []

    artefacts: dict[str, dict] = {}
    for path in sorted(GENERATED.glob("*")):
        if path.suffix not in (".tex", ".pdf", ".csv"):
            continue
        # A .tex declares its author in its first line; a .pdf cannot, so for a figure
        # the OUT_* assignment is the only signal there is. Where both exist they must
        # agree, and that disagreement is what this catches.
        if path.suffix == ".tex":
            match = _HEADER.search(path.read_text())
            script = match.group(1) if match else None
            if script is None:
                problems.append(f"{path.name}: no '% Generated by' header")
            built = produced_by.get(path.name)
            if script and built and built != script:
                problems.append(
                    f"{path.name}: header says {script}, {built} declares the output"
                )
        else:
            script = produced_by.get(path.name)
            if script is None:
                problems.append(f"{path.name}: no script declares this output")
        artefacts[path.name] = {
            "script": script,
            "step": step_of.get(script or ""),
            "hook": script in by_hook,
            # LaTeX includes a figure without its extension.
            "used_in": sorted(figures.get(path.stem, ()) or used.get(path.name, ())),
        }

    # A figure the thesis includes but that is not on disk does not fail the build:
    # every \includegraphics sits inside \IfFileExists, which substitutes a box telling
    # the reader to generate it. That is the right fallback for files kept out of the
    # repository, and it is also why a figure can go missing, or stay years old, with
    # nothing protesting. Nothing else checks this, so it is checked here.
    on_disk = {path.name for path in GENERATED.glob("*")}
    for name, places in sorted(figures.items()):
        if name in on_disk or f"{name}.pdf" in on_disk:
            continue
        where = ", ".join(places)
        problems.append(
            f"{name}.pdf: included by {where} but not in thesis/generated/ -- "
            "the build will show a placeholder box in its place"
        )

    macros = {
        name: {"file": source, "used_in": sorted(used.get(name, ()))}
        for name, source in defines.items()
    }
    # A .tex of macros is never included by name -- what the thesis quotes are the
    # macros inside it -- so the file is used wherever any of its macros is.
    for info in macros.values():
        entry = artefacts.get(info["file"])
        if entry is not None:
            entry["used_in"] = sorted(set(entry["used_in"]) | set(info["used_in"]))

    return artefacts, macros, problems


def family(name: str) -> str:
    """``StatVarParaAlphaOrderOne`` -> ``StatVar``, the grouping the thesis reads by."""
    if name.startswith("Preproc"):
        return "Preproc"
    match = re.match(r"(Stat[A-Z][a-z]+)", name)
    return match.group(1) if match else name


def _link(script: str | None) -> str:
    """A script as a link into the repository, or an em dash if it is unknown."""
    return f"[`{script}`](../../{script})" if script else "—"


def _when(info: dict) -> str:
    """How an artefact gets rebuilt: a chain step, the commit hook, or by hand."""
    if info["step"]:
        return f"step {info['step']}"
    return "pre-commit hook" if info["hook"] else "run by hand"


def render(artefacts: dict, macros: dict) -> str:
    """The page: the files, then the macro families, then what is written unused."""
    lines = [
        "<!-- Generated by scripts/reporting/generate_provenance.py. Do not edit. -->",
        "# Where each number and figure comes from",
        "",
        "Every number the thesis quotes and every figure it draws is written by a",
        "script, from the archive on the SSD. This page is the index in the other",
        "direction: from what is on the page back to the code that produced it. It is",
        "regenerated by",
        "`generate_provenance.py`, so it cannot drift from the repository.",
        "",
        "## The generated files",
        "",
        "| file | written by | rebuilt | used in |",
        "|---|---|---|---|",
    ]
    for name, info in sorted(artefacts.items()):
        used = ", ".join(f"`{u}`" for u in info["used_in"]) or "—"
        lines.append(f"| `{name}` | {_link(info['script'])} | {_when(info)} | {used} |")

    grouped: dict[str, list[str]] = defaultdict(list)
    for name in macros:
        grouped[family(name)].append(name)

    lines += [
        "",
        "## The macro families",
        "",
        "Each family is written by one script into one file. The count is how many",
        "macros that file defines; the sections are where the thesis quotes them.",
        "",
        "| family | file | written by | quoted in | macros |",
        "|---|---|---|---|---|",
    ]
    for fam, names in sorted(grouped.items()):
        source = macros[names[0]]["file"]
        script = artefacts.get(source, {}).get("script")
        places = sorted({p for n in names for p in macros[n]["used_in"]})
        used = ", ".join(f"`{p}`" for p in places) or "**not quoted**"
        lines.append(
            f"| `\\{fam}*` | `{source}` | {_link(script)} | {used} | {len(names)} |"
        )

    lines += [
        "",
        "## Written but not quoted",
        "",
        "A generator may legitimately write more than the current draft uses: a macro",
        "dropped from the text in a revision, or one written for a section not yet",
        "drafted. They are listed so the difference stays visible, not because a macro",
        "here is wrong.",
        "",
    ]
    unquoted: dict[str, list[str]] = defaultdict(list)
    for name, info in macros.items():
        if not info["used_in"]:
            unquoted[info["file"]].append(name)
    if unquoted:
        for source, names in sorted(unquoted.items()):
            listed = ", ".join(f"`\\{n}`" for n in sorted(names))
            lines.append(f"- `{source}` — {listed}")
    else:
        lines.append("Every macro a generator writes is quoted somewhere.")
    return "\n".join(lines) + "\n"


def main() -> int:
    """Write the page, or check the chain and report what is broken."""
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="report broken provenance and exit non-zero; write nothing",
    )
    args = parser.parse_args()

    artefacts, macros, problems = collect()
    if args.check:
        for problem in problems:
            print(f"provenance: {problem}", file=sys.stderr)
        print(f"{len(artefacts)} files, {len(macros)} macros, {len(problems)} problems")
        return 1 if problems else 0

    OUT_MD.parent.mkdir(parents=True, exist_ok=True)
    OUT_MD.write_text(render(artefacts, macros))
    where = OUT_MD.relative_to(ROOT)
    print(f"Wrote {where}: {len(artefacts)} files, {len(macros)} macros.")
    for problem in problems:
        print(f"  note: {problem}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
