#!/usr/bin/env python3
"""Generate LaTeX dataset statistics for the thesis document.

Reads the repository-versioned ``data/seasons_index.csv`` (one row per season:
``n_flights``, ``n_with_igc``, ``n_downloaded``) and writes two auto-generated LaTeX
files, included by ``thesis/main.tex``:

* ``thesis/generated/stats.tex``         -- ``\\newcommand`` macros with the headline
  numbers (totals, coverage, season range, generation date);
* ``thesis/generated/seasons_table.tex`` -- a ``longtable`` with the per-season counts.

The script is deterministic and has no third-party dependencies, so it can run both in
a git hook and in CI. It reads only the committed CSV (never the external disk), so the
numbers always match what is in the repository.
"""

from __future__ import annotations

import csv
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CSV_PATH = ROOT / "data" / "seasons_index.csv"
OUT_DIR = ROOT / "thesis" / "generated"

_AUTOGEN = "% AUTO-GENERATED by scripts/reporting/generate_stats.py -- DO NOT EDIT.\n"


def _season_label(raw: str) -> str:
    """Turn ``"1999-2000"`` into the LaTeX en-dash form ``"1999--2000"``."""
    return raw.replace("-", "--")


def _pct(part: int, whole: int) -> float:
    """Percentage ``part/whole`` (one decimal), ``0.0`` if ``whole`` is zero."""
    return round(100.0 * part / whole, 1) if whole else 0.0


def _read_rows() -> list[dict[str, str]]:
    """Read and return the rows of ``seasons_index.csv``."""
    with CSV_PATH.open(newline="", encoding="utf-8") as fh:
        return list(csv.DictReader(fh))


def _write_macros(rows: list[dict[str, str]]) -> None:
    """Write the headline-number macros to ``stats.tex``."""
    n_flights = sum(int(r["n_flights"]) for r in rows)
    n_with_igc = sum(int(r["n_with_igc"]) for r in rows)
    n_downloaded = sum(int(r["n_downloaded"]) for r in rows)
    lines = [
        _AUTOGEN,
        f"\\newcommand{{\\StatGenerated}}{{{date.today().isoformat()}}}\n",
        f"\\newcommand{{\\StatNumSeasons}}{{{len(rows)}}}\n",
        f"\\newcommand{{\\StatSeasonFirst}}{{{_season_label(rows[0]['season'])}}}\n",
        f"\\newcommand{{\\StatSeasonLast}}{{{_season_label(rows[-1]['season'])}}}\n",
        f"\\newcommand{{\\StatTotalFlights}}{{{n_flights}}}\n",
        f"\\newcommand{{\\StatWithIgc}}{{{n_with_igc}}}\n",
        f"\\newcommand{{\\StatDownloaded}}{{{n_downloaded}}}\n",
        f"\\newcommand{{\\StatPctWithIgc}}{{{_pct(n_with_igc, n_flights)}}}\n",
        f"\\newcommand{{\\StatPctDownloaded}}{{{_pct(n_downloaded, n_with_igc)}}}\n",
    ]
    (OUT_DIR / "stats.tex").write_text("".join(lines), encoding="utf-8")


def _write_table(rows: list[dict[str, str]]) -> None:
    """Write the per-season ``longtable`` to ``seasons_table.tex``."""
    out = [
        _AUTOGEN,
        "\\begin{longtable}{l S S S S}\n",
        "\\caption{FFVL CFD flights per season: total declared, with a GPS track, and "
        "downloaded. Source: \\texttt{data/seasons\\_index.csv}.}"
        "\\label{tab:seasons}\\\\\n",
        "\\toprule\n",
        "Season & {Flights} & {With GPS} & {Downloaded} & {Coverage (\\%)} \\\\\n",
        "\\midrule\n\\endfirsthead\n",
        "\\toprule\n",
        "Season & {Flights} & {With GPS} & {Downloaded} & {Coverage (\\%)} \\\\\n",
        "\\midrule\n\\endhead\n",
        "\\midrule\n\\endfoot\n",
        "\\bottomrule\n\\endlastfoot\n",
    ]
    tot_f = tot_i = tot_d = 0
    for r in rows:
        n_f, n_i, n_d = int(r["n_flights"]), int(r["n_with_igc"]), int(r["n_downloaded"])
        tot_f += n_f
        tot_i += n_i
        tot_d += n_d
        out.append(
            f"{_season_label(r['season'])} & {n_f} & {n_i} & {n_d} & "
            f"{_pct(n_d, n_i)} \\\\\n"
        )
    out.append("\\midrule\n")
    out.append(
        f"\\textbf{{Total}} & {tot_f} & {tot_i} & {tot_d} & {_pct(tot_d, tot_i)} \\\\\n"
    )
    out.append("\\end{longtable}\n")
    (OUT_DIR / "seasons_table.tex").write_text("".join(out), encoding="utf-8")


def main() -> int:
    """Generate both LaTeX files; return a process exit code."""
    if not CSV_PATH.is_file():
        raise SystemExit(f"Missing {CSV_PATH}. Refresh it with 'soaring-para build-catalog'.")
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    rows = _read_rows()
    _write_macros(rows)
    _write_table(rows)
    print(f"Wrote {OUT_DIR}/stats.tex and seasons_table.tex from {len(rows)} seasons.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
