#!/usr/bin/env python3
"""Generate the git-history timeline for the private logbook.

A logbook is the succession of events, and every git commit is an event. This script
turns ``git log`` into a LaTeX ``longtable`` (date + subject), written to
``logbook/generated/timeline.tex`` and included by ``logbook/logbook.tex``.

It complements the hand-written narrative notes (the "why", what failed, decisions),
which live in ``logbook/logbook.tex`` and are not generated.

Note: when run from a pre-commit hook the commit being created is not in ``git log``
yet, so the timeline trails by one commit; it catches up at the next build.
"""

from __future__ import annotations

import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "logbook" / "generated" / "timeline.tex"

_AUTOGEN = "% AUTO-GENERATED by scripts/reporting/generate_timeline.py -- DO NOT EDIT.\n"

# LaTeX special characters that must be escaped in commit subjects.
_ESCAPE = {
    "\\": r"\textbackslash{}",
    "&": r"\&",
    "%": r"\%",
    "$": r"\$",
    "#": r"\#",
    "_": r"\_",
    "{": r"\{",
    "}": r"\}",
    "~": r"\textasciitilde{}",
    "^": r"\textasciicircum{}",
}


def _escape(text: str) -> str:
    """Escape LaTeX special characters in ``text``."""
    return "".join(_ESCAPE.get(ch, ch) for ch in text)


def _git_log() -> list[tuple[str, str]]:
    """Return ``(date, subject)`` pairs from ``git log``, newest first."""
    result = subprocess.run(
        ["git", "-C", str(ROOT), "log", "--date=short", "--pretty=%ad%x09%s"],
        capture_output=True,
        text=True,
        check=True,
    )
    pairs: list[tuple[str, str]] = []
    for line in result.stdout.splitlines():
        if "\t" in line:
            day, subject = line.split("\t", 1)
            pairs.append((day, subject))
    return pairs


def main() -> int:
    """Write the timeline table; return a process exit code."""
    OUT.parent.mkdir(parents=True, exist_ok=True)
    entries = _git_log()
    out = [
        _AUTOGEN,
        "\\begin{longtable}{l p{0.78\\linewidth}}\n",
        "\\toprule\n",
        "Date & Event (commit subject) \\\\\n",
        "\\midrule\n\\endhead\n",
    ]
    for day, subject in entries:
        out.append(f"{day} & {_escape(subject)} \\\\\n")
    out.append("\\bottomrule\n\\end{longtable}\n")
    OUT.write_text("".join(out), encoding="utf-8")
    print(f"Wrote {OUT} with {len(entries)} commits.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
