"""Render regional finite-difference figures from a completed aggregate report."""

# ruff: noqa: E402 -- direct entry point bootstraps this checkout's source path
from __future__ import annotations

import argparse
import gzip
import hashlib
import json
import sys
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT / "src"))

from soaring.reporting.regional_variations import (
    render_regional_variations,
    variation_macros,
)


def main():
    """Save figures and a manifest linking every output to the numerical report."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--report", type=Path, required=True)
    parser.add_argument("--out", type=Path, default=ROOT / "thesis/generated")
    parser.add_argument("--manifest", type=Path, required=True)
    args = parser.parse_args()
    raw = args.report.read_bytes()
    if args.report.suffix == ".gz":
        raw = gzip.decompress(raw)
    report = json.loads(raw)
    if report["status"] != "complete":
        raise ValueError("A completed numerical report is required")
    paths = render_regional_variations(report, args.out)
    values = args.out / "ch3_regional_variations_values.tex"
    values.write_text(
        "% Generated by scripts/reporting/ch3_global_transport/"
        "generate_regional_variations.py -- do not edit.\n"
        + "".join(
            "\\newcommand{\\" + key + "}{" + value + "}\n"
            for key, value in variation_macros(report).items()
        )
    )
    paths.append(values)
    record = {
        "run_id": report["run_id"],
        "report_raw_sha256": hashlib.sha256(raw).hexdigest(),
        "operation": "render saved complete report; no new measurements or fits",
        "sources": {
            str(p.relative_to(ROOT)): hashlib.sha256(p.read_bytes()).hexdigest()
            for p in (
                Path(__file__),
                ROOT / "src/soaring/reporting/regional_variations.py",
            )
        },
        "outputs": {p.name: hashlib.sha256(p.read_bytes()).hexdigest() for p in paths},
    }
    args.manifest.write_text(json.dumps(record, indent=2) + "\n")
    print(f"Rendered {len(paths)} regional variation figures")


if __name__ == "__main__":
    main()
