"""Slide 11 and the slide-9 notes check: expert--beginner and regional contrasts on open circuits only.

Same fixed cohort C_10000, equal-flight TA-MSD, 10-10,000 s fit and archived paired
site-day draws as thesis Sections 3.2.3-3.2.4 (conditional_ch3_transport.py); the
only new step is the open-circuit filter. All SSD inputs are read-only.
"""
from pathlib import Path
import json
import sys

import numpy as np

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT / "scripts/tesi/ch03_fixed_transport"))
from check_bootstrap_reliability import load_inputs, signature
from summarize_ch3_fixed import fit_summary, portable, summary

from soaring.analysis.observables.conditional_transport import strata
from soaring.analysis.observables.fixed_bootstrap import bootstrap_means
from soaring.analysis.observables.fixed_transport import LAGS, log_fit

HERE = Path(__file__).resolve().parent
RUN = Path("/Volumes/SSD_DISANTE/derived-audit/chapter3-fixed-20260917")
PUBLISHED = json.loads((ROOT / "thesis/generated/ch3_conditional.json").read_text())
REGIONS = ("alps", "pyrenees", "channel_coast", "champagne_lorraine")
# Published all-circuit groups; each is measured again on its open circuits only.
GROUPS = [*REGIONS, "beginners", "experts",
          *(f"{g}_alt{i}" for g in ("beginners", "experts") for i in range(4))]
CONTRASTS = {"mountain_regions": [("alps", 1), ("pyrenees", -1)],
             "lowland_regions": [("channel_coast", 1), ("champagne_lorraine", -1)],
             "experts_beginners": [("experts", 1), ("beginners", -1)]}
for i in range(4):
    CONTRASTS[f"equipment_alt{i}"] = [(f"experts_alt{i}", 1), (f"beginners_alt{i}", -1)]
    for j in range(i + 1, 4):
        CONTRASTS[f"equipment_interaction_{i}_{j}"] = [
            (f"experts_alt{i}", 1), (f"beginners_alt{i}", -1),
            (f"experts_alt{j}", -1), (f"beginners_alt{j}", 1)]

reference = json.loads((RUN / "report.json").read_text())
frame, cohort, values, _, provenance = load_inputs(RUN, "para", reference)
members = frame.loc[cohort].copy()
masks = strata(members)
labels = members.cluster.to_numpy(dtype=int)
archived = np.load(RUN / "para/cluster-draws.npy", mmap_mode="r")


def measure(mask):
    """Group mean curve with the archived draws, restricted to occupied clusters."""
    occupied, local = np.unique(labels[mask], return_inverse=True)
    curve = bootstrap_means(values[mask], local, archived[:, occupied])
    if not np.isfinite(curve).all() or (curve <= 0).any():
        raise ValueError("Incomplete bootstrap support")
    return curve, len(occupied)


groups, exponents = {}, {}
for key in GROUPS:
    # The published all-circuit group must be reproduced before filtering.
    curve, _ = measure(masks[key])
    np.testing.assert_allclose(curve[0], PUBLISHED["groups"][key]["msd"]["point"], rtol=1e-10)
    mask = masks[key] & masks["open"]
    curve, clusters = measure(mask)
    exponents[key] = log_fit(LAGS, curve)["slope"] / 2
    groups[key] = {"flights": int(mask.sum()), "clusters": clusters,
                   "all_circuit_flights": int(masks[key].sum()),
                   "msd": summary(curve), "fit": fit_summary(LAGS, curve, (10, 10000))}
    print(f"{key}: {mask.sum()} open flights, H={exponents[key][0]:.4f}", flush=True)
contrasts = {name: {"terms": terms, "hurst": summary(sum(w * exponents[g] for g, w in terms))}
             for name, terms in CONTRASTS.items()}
report = portable({
    "status": "complete",
    "source_report": signature(RUN / "report.json"),
    "source_files": provenance,
    "measurement_script": signature(Path(__file__)),
    "contract": {**PUBLISHED["contract"], "circuit": "open only"},
    "lags_s": LAGS,
    "groups": groups,
    "contrasts": contrasts,
})
(HERE / "open-circuits-report.json").write_text(json.dumps(report, indent=2, allow_nan=False) + "\n")


def interval(item):
    return rf"${item['point']:.3f}\;[{item['low']:.3f},\,{item['high']:.3f}]$"


def tag(key):
    """TeX control-sequence suffix; digits spelled out as in the thesis macros."""
    for i, word in enumerate(("Zero", "One", "Two", "Three")):
        key = key.replace(str(i), word)
    return "".join(part[:1].upper() + part[1:] for part in key.split("_"))


macros = []
for key, row in report["groups"].items():
    macros += [rf"\newcommand{{\Open{tag(key)}H}}{{{interval(row['fit']['hurst'])}}}",
               rf"\newcommand{{\Open{tag(key)}N}}{{{row['flights']}}}"]
for key, row in report["contrasts"].items():
    macros.append(rf"\newcommand{{\Open{tag(key)}Delta}}{{{interval(row['hurst'])}}}")
(HERE / "open-circuits-values.tex").write_text(
    "% Generated by measure_open_circuits.py: open circuits only.\n" + "\n".join(macros) + "\n")
print("Completed", flush=True)
