r"""A macro name LaTeX cannot accept has to fail at the generator, not at the build.

``\newcommand{\StatMsdParaCohortAlpha1H}{1.42}`` does not define a macro whose name
ends in ``1H``. It defines ``\StatMsdParaCohortAlpha`` taking one argument, and leaves
``H}{1.42}`` as text -- twelve errors and a stopped build, diagnosed from a symptom that
names the wrong line, and reachable from a definition nothing quotes. It happened. These
tests pin the refusal to the point where the name is written.
"""

from __future__ import annotations

import pytest

from soaring.reporting import DISCIPLINES, MacroNameError, MacroWriter, write_macros
from soaring.reporting.macros import pct_of, pct_true, tex_int


@pytest.mark.parametrize(
    "name",
    ["StatMsdParaCohortAlpha1H", "Stat_Msd", "StatMsdPara ", "Stat2", "", "StatParaÉ"],
)
def test_put_refuses_a_name_latex_cannot_parse(name):
    with pytest.raises(MacroNameError):
        MacroWriter().put(name, 1)


def test_put_applies_the_prefix_and_stringifies():
    writer = MacroWriter("StatMsdPara")
    writer.put("Alpha", 1.42)
    writer.put("Flights", 155788)
    assert writer.macros == {"StatMsdParaAlpha": "1.42", "StatMsdParaFlights": "155788"}
    assert len(writer) == 2


def test_the_prefix_is_validated_too():
    """A valid suffix on an invalid prefix is still an invalid control sequence."""
    with pytest.raises(MacroNameError):
        MacroWriter("StatMsd1").put("Alpha", 1)


def test_write_refuses_the_whole_file_rather_than_part_of_it(tmp_path):
    out = tmp_path / "msd.tex"
    with pytest.raises(MacroNameError):
        write_macros(out, {"StatGood": "1", "StatBad1H": "2"}, generator="t.py")
    assert not out.exists(), "a rejected file must not be left half-written"


def test_write_keeps_insertion_order_unless_asked_to_sort(tmp_path):
    macros = {"StatB": "2", "StatA": "1"}
    out = tmp_path / "a.tex"
    write_macros(out, macros, generator="t.py")
    assert out.read_text().splitlines()[1:] == [
        r"\newcommand{\StatB}{2}",
        r"\newcommand{\StatA}{1}",
    ]
    write_macros(out, macros, generator="t.py", sort=True)
    assert out.read_text().splitlines()[1:] == [
        r"\newcommand{\StatA}{1}",
        r"\newcommand{\StatB}{2}",
    ]


def test_write_is_reproducible_and_headed_by_its_generator(tmp_path):
    out = tmp_path / "a.tex"
    count = write_macros(
        out,
        MacroWriter("Stat"),
        generator="scripts/reporting/x.py",
        extra_header=["why"],
    )
    assert count == 0
    first = out.read_text()
    assert first.splitlines()[:2] == [
        "% Generated by scripts/reporting/x.py -- do not edit.",
        "% why",
    ]
    write_macros(
        out,
        MacroWriter("Stat"),
        generator="scripts/reporting/x.py",
        extra_header=["why"],
    )
    assert out.read_text() == first


def test_disciplines_are_distinct_in_every_field_a_filename_or_macro_uses():
    """A shared slug or tag would overwrite one discipline's output with the other's."""
    for field in ("name", "slug", "tag", "env", "config_attr", "color"):
        values = [getattr(d, field) for d in DISCIPLINES.values()]
        assert len(set(values)) == len(values), field


def test_derived_dir_is_none_rather_than_raising_without_an_archive(monkeypatch):
    """A fresh checkout has no SSD; that is the normal state, not an error."""
    monkeypatch.setenv("SOARING_PARA_DATA_ROOT", "/nonexistent/soaring-test")
    assert DISCIPLINES["paragliders"].derived_dir() is None


def test_formatters():
    assert tex_int(1363998292) == "1{,}363{,}998{,}292"
    assert tex_int(42.9) == "42"
    assert pct_of(1, 4) == 25.0
    assert pct_of(1, 0) == 0.0, "an empty total is 0 %, never a division error"
    assert pct_true([True, False, True, True]) == 75.0
    assert pct_true([]) == 0.0, "an empty slice is 0 %, never the string 'nan'"
