"""MSD contribution of each circuit within each initial-altitude class."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

from conditional_plot_style import ALTITUDE_COLORS


PREFIX = "ch3_conditional_circuit_weights"
NAMES = ["Plains", "Hills", "Low mountains", "High mountains"]


def compute_weights(report):
    """Keep the full altitude class, including unclassified flights, as denominator."""
    groups = report["groups"]
    rows = []
    for i, name in enumerate(NAMES):
        group = groups[f"alt{i}"]
        total = np.asarray(group["msd"]["point"], dtype=float)
        row = {"class": name, "flights": group["flights"]}
        for circuit in ("open", "closed"):
            cell = groups[f"{circuit}_{i}"]
            p = cell["flights"] / group["flights"]
            row[f"p_{circuit}"] = p
            row[f"w_{circuit}"] = (p * np.asarray(cell["msd"]["point"]) / total).tolist()
        residual = 1 - np.asarray(row["w_open"]) - np.asarray(row["w_closed"])
        if (residual < -1e-12).any() or (residual > 1 + 1e-12).any():
            raise ValueError(f"Invalid unclassified contribution: {name}")
        if group["circuit_counts"].get("unknown", 0) == 0:
            np.testing.assert_allclose(residual, 0, atol=1e-12)
        row["w_unclassified"] = residual.tolist()
        rows.append(row)
    return {"lags_s": report["lags_s"], "classes": rows}


def plot_weights(data, path, *, colors=None, figsize=(7.1, 3.5), fontsize=9):
    colors = colors or list(ALTITUDE_COLORS.values())
    with plt.rc_context({"font.family": "serif", "font.size": fontsize, "pdf.fonttype": 42}):
        fig, axes = plt.subplots(1, 2, figsize=figsize, sharex=True, sharey=True, layout="constrained")
        for ax, circuit in zip(axes, ("open", "closed"), strict=True):
            for row, color in zip(data["classes"], colors, strict=True):
                ax.plot(data["lags_s"], row[f"w_{circuit}"], color=color, lw=1.8, label=row["class"])
            ax.set(xscale="log", xlim=(10, 10000), ylim=(-0.02, 1.04),
                   xlabel=r"Lag $\tau$ (s)", title=f"{circuit.capitalize()} contribution within each altitude class")
            ax.set_title(ax.get_title(), fontsize=fontsize)
            ax.grid(alpha=0.22)
            ax.spines[["top", "right"]].set_visible(False)
        axes[0].set_ylabel(r"Share of the class MSD, $w_{c\mid a}(\tau)$")
        axes[0].legend(loc="upper left", bbox_to_anchor=(0.015, 0.78),
                       frameon=False, fontsize=fontsize - 1)
        fig.savefig(path, bbox_inches="tight", metadata={"CreationDate": None, "ModDate": None})
        plt.close(fig)


def publish_weights(report, out):
    out = Path(out)
    out.mkdir(parents=True, exist_ok=True)
    data = compute_weights(report)
    data["source_sha256"] = hashlib.sha256(
        json.dumps(report, sort_keys=True).encode()
    ).hexdigest()
    data["definition"] = "w_c|a = (N_c,a/N_a) M_c,a / M_a; full altitude-class denominator"
    data["uncertainty"] = "Observed contribution shares only; no confidence bands estimated"
    plot_weights(data, out / f"{PREFIX}.pdf")
    macros = ["% Generated by circuit_msd_weights.py from the conditional report."]
    for row in data["classes"]:
        tag = "".join(word.capitalize() for word in row["class"].split())
        for circuit in ("open", "closed"):
            macros.append(
                rf"\newcommand{{\CircuitWeight{tag}{circuit.capitalize()}End}}{{{100 * row[f'w_{circuit}'][-1]:.1f}}}"
            )
    max_unknown = max(max(row["w_unclassified"]) for row in data["classes"])
    macros.append(rf"\newcommand{{\CircuitWeightUnknownMax}}{{{100 * max_unknown:.2f}}}")
    (out / f"{PREFIX}_values.tex").write_text("\n".join(macros) + "\n")
    (out / f"{PREFIX}.json").write_text(json.dumps(data, indent=2, allow_nan=False) + "\n")
    return data


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--report", type=Path, default=Path("thesis/generated/ch3_conditional.json"))
    parser.add_argument("--out", type=Path, default=Path("thesis/generated"))
    args = parser.parse_args()
    result = publish_weights(json.loads(args.report.read_text()), args.out)
    for row in result["classes"]:
        print(row["class"], "open share at 10000 s:", f"{row['w_open'][-1]:.4%}")
