r"""Numerical macros generated from the validated Chapter 3 report.

The chapter prose lives in `thesis/tesi/04-fixed-transport.tex` so that it can be
read and edited directly. This module supplies only the numbers it cites, as
`\newcommand` definitions collected in `ch3_transport_values.tex`. Claims whose
wording depends on a comparison holding are guarded by assertions here: if one
stops holding, the run fails and the sentence must be rewritten by hand.
"""

from __future__ import annotations

import numpy as np

SLUGS = ("para", "hang")


def interval(stats, index=None, digits=3):
    """Render a point estimate and central percentile interval."""
    values = [np.asarray(stats[k]) for k in ("point", "low", "high")]
    if index is not None:
        values = [v[index] for v in values]
    return f"{values[0]:.{digits}f} [{values[1]:.{digits}f}, {values[2]:.{digits}f}]"


class Macros:
    """Collect uniquely named LaTeX definitions for the chapter to cite."""

    def __init__(self) -> None:
        """Start with no definitions."""
        self.items: dict[str, str] = {}

    def add(self, name, value):
        """Define one macro, refusing a silent redefinition."""
        if name in self.items:
            raise ValueError(f"Duplicate macro {name}")
        self.items[name] = str(value)

    def per_discipline(self, suffix, values):
        """Define the same quantity for paragliders and hang gliders."""
        for slug, value in zip(SLUGS, values, strict=True):
            self.add(f"ChThree{slug.capitalize()}{suffix}", value)

    def render(self):
        """Emit the definitions in a stable order for a reviewable diff."""
        return (
            "% Generated by scripts/tesi/ch03_fixed_transport/write_ch3_text.py\n"
            "% Chapter prose is hand-written; only these values are generated.\n"
            + "\n".join(
                f"\\newcommand{{\\{name}}}{{{value}}}"
                for name, value in sorted(self.items.items())
            )
            + "\n"
        )


def write_text(report, out):
    """Keep the values cited by the chapter synchronised with the plots."""
    results = report["results"]
    m = Macros()

    m.per_discipline(
        "PriorInterp",
        [
            f"{results[s]['interpolation']['10000']['grid_exact_previously_interpolated']:,}"
            for s in SLUGS
        ],
    )

    general = [results[s]["general"]["tamsd_global_fit"] for s in SLUGS]
    m.per_discipline("GeneralHurst", [interval(g["hurst"]) for g in general])
    m.add("ChThreeHangGeneralGroups", general[1]["minimum_group_support"])
    m.add("ChThreeHangGeneralReplicates", general[1]["valid_bootstrap_replicates"])

    def save(name, paragraphs):
        (out / f"ch3_transport_{name}.tex").write_text("\n\n".join(paragraphs) + "\n")

    diagnostics = [results[s]["cluster_diagnostics"] for s in SLUGS]

    def median_range(item, key, spatial=False):
        low, median, high = item[key]["p10_median_p90"]
        if spatial:
            return f"{median:.1f} [{low:.2f}, {high:.0f}]"
        return f"{median:.0f} [{low:.0f}, {high:.0f}]"

    rows = [
        ("Catalogue sites", [f"{s['sites']:,}" for s in diagnostics]),
        ("Calendar dates", [f"{s['dates']:,}" for s in diagnostics]),
        (
            "Flights per group: median / P95 / max",
            [
                " / ".join(f"{v:.0f}" for v in s["size_min_median_p95_max"][1:])
                for s in diagnostics
            ],
        ),
        (
            r"Largest group (\% of flights)",
            [f"{100 * s['largest_group_flight_fraction']:.2f}" for s in diagnostics],
        ),
        (
            "Nearest same-day site (km)",
            [median_range(s, "same_day_nearest_km", True) for s in diagnostics],
        ),
        (
            "Spatial comparisons",
            [f"{s['same_day_nearest_km']['n']:,}" for s in diagnostics],
        ),
        (
            "Prior observed date at same site: gap (days)",
            [median_range(s, "previous_observed_day_gap") for s in diagnostics],
        ),
        (
            "Temporal comparisons",
            [f"{s['previous_observed_day_gap']['n']:,}" for s in diagnostics],
        ),
        (
            "Flights with missing site/date keys",
            [f"{s['missing_key_flights']:,}" for s in diagnostics],
        ),
    ]
    lines = [
        r"\begin{tabular}{lrr}",
        r"\toprule",
        r"Quantity & Paragliders & Hang gliders \\",
        r"\midrule",
    ]
    lines.extend(
        label + " & " + " & ".join(entries) + r" \\" for label, entries in rows
    )
    lines.extend([r"\bottomrule", r"\end{tabular}"])
    save("cluster_context", ["\n".join(lines)])

    for slug in SLUGS:
        cohorts = results[slug]["cohorts"]
        for suffix, key in (("Start", "100"), ("Main", "10000")):
            cohort = cohorts[key]
            fraction = 100 * cohort["task_counts"].get("closed", 0) / cohort["flights"]
            m.add(f"ChThree{slug.capitalize()}ClosedFrac{suffix}", f"{fraction:.1f}")

    # The chapter states that the two broad cohorts differ by less than 1e-4 on
    # 10--100 s, and that every comparison with the main cohort excludes zero.
    main_contrasts = []
    bias_pct = []
    shift_abs = []
    for d in results.values():
        comparisons = d["cohort_h_comparisons"]
        broad = comparisons["10-100"]["contrasts"]["100_minus_1000"]
        if abs(broad["point"]) >= 1e-4:
            raise ValueError("Rewrite the cohort effect-size sentence: |diff| >= 1e-4")
        for comparison in comparisons.values():
            main_h = comparison["fits"]["10000"]["hurst"]["point"]
            for key, contrast in comparison["contrasts"].items():
                if key.endswith("minus_10000"):
                    main_contrasts.append(contrast)
                    shift_abs.append(abs(contrast["point"]))
                    bias_pct.append(100 * abs(contrast["point"]) / main_h)
    if not all(contrast["high"] < 0 for contrast in main_contrasts):
        raise ValueError(
            "Rewrite the cohort comparison sentence: a paired interval includes zero"
        )
    # The chapter reports this range as "on the order of 2%"; keep the sentence
    # honest if a remeasurement ever pushes the bias outside that description.
    if not 0.5 <= min(bias_pct) <= max(bias_pct) <= 5.0:
        raise ValueError(
            "Rewrite the cohort bias sentence: relative |Delta H| left the 0.5-5% band"
        )
    m.add("ChThreeCohortBiasMinPct", f"{min(bias_pct):.1f}")
    m.add("ChThreeCohortBiasMaxPct", f"{max(bias_pct):.1f}")
    m.add("ChThreeCohortShiftMin", f"{min(shift_abs):.4f}")
    m.add("ChThreeCohortShiftMax", f"{max(shift_abs):.4f}")

    # C_1000 is nested in C_100, so its flight count over C_100's is the share of
    # flights the two cohorts have in common.
    for slug in SLUGS:
        cohorts = results[slug]["cohorts"]
        share = 100 * cohorts["1000"]["flights"] / cohorts["100"]["flights"]
        m.add(f"ChThree{slug.capitalize()}CohortOverlapPct", f"{share:.1f}")

    d = results["para"]
    for label, counts, n in (
        ("Eligible", d["eligible_task_counts"], d["eligible_flights"]),
        (
            "Main",
            d["cohorts"]["10000"]["task_counts"],
            d["cohorts"]["10000"]["flights"],
        ),
    ):
        for task in ("open", "closed"):
            m.add(f"ChThree{label}{task.capitalize()}", f"{counts[task]:,}")
            m.add(
                f"ChThree{label}{task.capitalize()}Pct", f"{100 * counts[task] / n:.1f}"
            )
        m.add(f"ChThree{label}Unknown", f"{counts.get('unknown', 0):,}")
    contrasts = d["hurst_contrasts"]
    direct = [contrasts[f"open_minus_closed_{i}"] for i in range(4)]
    # The chapter states that every open-minus-closed interval excludes zero.
    if not all(c["low"] > 0 for c in direct):
        raise ValueError(
            "Rewrite the circuit contrast sentence: a paired interval includes zero"
        )
    m.add("ChThreeTaskContrastMin", f"{min(c['point'] for c in direct):.3f}")
    m.add("ChThreeTaskContrastMax", f"{max(c['point'] for c in direct):.3f}")

    # Lowland (Plains, Hills) against mountain (Low, High) launch classes, within
    # each circuit. The chapter reads the opposite signs as one orographic effect,
    # so the signs themselves are guarded, not only the exclusion of zero.
    lowland = [
        (task, contrasts[f"{task}_{i}_minus_{j}"])
        for task in ("open", "closed")
        for i in (0, 1)
        for j in (2, 3)
    ]
    if not all(c["low"] > 0 for task, c in lowland if task == "open"):
        raise ValueError(
            "Rewrite the circuit orography paragraph: an open lowland-minus-mountain "
            "contrast is no longer positive with the zero excluded"
        )
    if not all(c["high"] < 0 for task, c in lowland if task == "closed"):
        raise ValueError(
            "Rewrite the circuit orography paragraph: a closed lowland-minus-mountain "
            "contrast is no longer negative with the zero excluded"
        )
    for task, label in (("open", "Open"), ("closed", "Closed")):
        sizes = [abs(c["point"]) for other, c in lowland if other == task]
        m.add(f"ChThree{label}AltShiftMin", f"{min(sizes):.3f}")
        m.add(f"ChThree{label}AltShiftMax", f"{max(sizes):.3f}")

    for slug in SLUGS:
        g = results[slug]["general"]
        x = np.asarray(g["lags"])
        h = np.asarray(g["ensemble_local_h"], dtype=float)
        keep = np.flatnonzero((x >= 20) & (x <= 2000) & np.isfinite(h))
        j = keep[np.argmin(h[keep])]
        m.add(f"ChThree{slug.capitalize()}LocalMinLag", f"{x[j]:.0f}")
        m.add(f"ChThree{slug.capitalize()}LocalMinH", f"{h[j]:.2f}")

    for slug in SLUGS:
        d = results[slug]
        prefix = f"ChThree{slug.capitalize()}Quant"
        ratio = np.asarray(d["quantile_ratio"]["point"])[:, 2]
        x = np.asarray(d["lags"])
        early = np.flatnonzero(x <= 200)
        j = early[np.argmin(ratio[early])]
        # The early minimum is followed by a broad maximum before long-lag decline.
        late = np.flatnonzero((x >= 200) & (x <= 5000))
        k = late[np.argmax(ratio[late])]
        rms = np.asarray(d["scaling_fits"]["10-10000"]["quantile_rms_dex"]["point"])
        m.add(f"{prefix}RatioStart", f"{ratio[0]:.3f}")
        m.add(f"{prefix}RatioMin", f"{ratio[j]:.3f}")
        m.add(f"{prefix}RatioMinLag", f"{x[j]:.0f}")
        m.add(f"{prefix}RatioMax", f"{ratio[k]:.3f}")
        m.add(f"{prefix}RatioMaxLag", f"{x[k]:.0f}")
        m.add(f"{prefix}RatioEnd", f"{ratio[-1]:.3f}")
        m.add(f"{prefix}RmsMin", f"{rms.min():.3f}")
        m.add(f"{prefix}RmsMax", f"{rms.max():.3f}")

    for slug in SLUGS:
        s = results[slug]["scaling_fits"]["10-10000"]
        prefix = f"ChThree{slug.capitalize()}Moment"
        rms = np.asarray(s["moment_rms_dex"]["point"])
        m.add(f"{prefix}Contrast", interval(s["H4_minus_H025"], 2, digits=4))
        m.add(f"{prefix}RmsMin", f"{rms.min():.3f}")
        m.add(f"{prefix}RmsMax", f"{rms.max():.3f}")

    for slug in SLUGS:
        a = np.asarray(results[slug]["kurtosis"]["point"])
        prefix = f"ChThree{slug.capitalize()}Kurt"
        for suffix, row in (("Start", 0), ("End", -1)):
            m.add(f"{prefix}E{suffix}", f"{a[row, 0]:.2f}")
            m.add(f"{prefix}N{suffix}", f"{a[row, 1]:.2f}")

    (out / "ch3_transport_values.tex").write_text(m.render())
