"""Share of cleaned flight time by logging cadence, for the segmentation slides.

Reads the archived Vilpellet coverage tables (SSD, read-only) and writes
cadence-values.tex. Time is the sum of t_end - t_start over cleaned
preprocessing segments, so unsupported gaps are excluded. Vilpellet's code
admits a track only when its mean step is below 1.2 s.
"""
from pathlib import Path

import pandas as pd

HERE = Path(__file__).resolve().parent
TABLES = {
    "Para": "/Volumes/SSD_DISANTE/paragliders/ffvl_cfd_igc/derived/segmentation/vilpellet/phase_coverage.parquet",
    "Hang": "/Volumes/SSD_DISANTE/hang_gliders/delta_cfd_igc/derived/segmentation/vilpellet/phase_coverage.parquet",
}
# Cadence classes of the stacked bar: about 1 s, about 2 s, 3-5 s, slower.
BINS = {"One": (0, 1.2), "Two": (1.2, 2.5), "Five": (2.5, 5.5), "Slow": (5.5, float("inf"))}

lines = ["% Generated by measure_cadence.py from the 16 Sep 2026 coverage tables."]
for prefix, path in TABLES.items():
    table = pd.read_parquet(path)
    duration = table.t_end - table.t_start
    cadence = table.native_cadence_s
    share = lambda mask: 100 * duration[mask].sum() / duration.sum()
    values = {name: share((cadence >= lo) & (cadence < hi)) for name, (lo, hi) in BINS.items()}
    values["Lost"] = 100 - values["One"]
    # Flights with no segment below the gate: Vilpellet's HMM labels none of their fixes.
    eligible = table.assign(ok=cadence < 1.2).groupby("flight_id").ok.any()
    values["LostFlights"] = 100 * (~eligible).mean()
    values["UpToTen"] = share(cadence <= 10)
    values["Labelled"] = share(table.n_classified_fixes > 0)
    lines += [f"\\newcommand{{\\Cad{prefix}{name}}}{{{value:.1f}}}" for name, value in values.items()]
    lines.append(f"\\newcommand{{\\Cad{prefix}Hours}}{{{duration.sum() / 3600:,.0f}}}")

(HERE / "cadence-values.tex").write_text("\n".join(lines) + "\n")
print("\n".join(lines))
