"""Slide figure: C_v(n) of successive glides, paragliders, open vs closed, fixed cohort.

Reads glide-autocorrelation.csv (measure_glide_autocorrelation.py). Writes
assets/glide-autocorrelation-para.pdf and glide-autocorrelation-values.tex.
"""
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

HERE = Path(__file__).resolve().parent
CIRCUIT = {"open": "#3477A8", "closed": "#8E3B5C"}
SCALES = (("linear", False, False), ("semi-log $y$", True, False), ("log-log", True, True))

FIT_LAGS = (1, 33)  # straight line in semi-log y, open circuits only

table = pd.read_csv(HERE / "glide-autocorrelation.csv")
fit = table.loc[(table.task == "open") & table.lag.between(*FIT_LAGS)]
slope, intercept = np.polyfit(fit.lag, np.log(fit.C_v), 1)  # log C_v = intercept + slope * n

plt.rcParams.update({"font.family": "Palatino", "mathtext.fontset": "custom", "mathtext.rm": "Palatino",
                     "mathtext.it": "Palatino:italic", "font.size": 8.5, "axes.linewidth": .6})
fig, axes = plt.subplots(1, 3, figsize=(6.6, 2.36))
for ax, (title, logy, logx) in zip(axes, SCALES):
    for task, colour in CIRCUIT.items():
        d = table.loc[table.task == task]
        if logx:
            d = d.loc[d.lag >= 1]
        y = d.C_v.where(d.C_v > 0) if logy else d.C_v  # NaN breaks the line where C_v <= 0
        ax.plot(d.lag, y, color=colour, marker="o", ms=2.2, lw=1, label=f"{task} circuits")
    if logy and not logx:
        n = np.linspace(*FIT_LAGS, 50)
        line, = ax.plot(n, np.exp(intercept + slope * n), color="black", lw=.9, ls="--",
                        label=rf"fit $n={FIT_LAGS[0]}$–${FIT_LAGS[1]}$: $\propto e^{{-n/{-1 / slope:.0f}}}$")
        ax.legend(handles=[line], fontsize=7, frameon=False, loc="lower right")
    ax.set_title(title, fontsize=9)
    if logy:
        ax.set_yscale("log")
    else:
        ax.axhline(0, color="#999", lw=.6)
    if logx:
        ax.set_xscale("log")
    ax.set_xlabel("lag $n$ (glides)")
    ax.grid(True, which="major", alpha=.25, lw=.5)
    ax.tick_params(width=.6, length=2.5, labelsize=7.5)
axes[0].set_ylabel("$C_v(n)$")
# Closed circuits: where the curve crosses zero and where it bottoms out.
closed = table.loc[(table.task == "closed") & (table.lag >= 1)]
low = closed.loc[closed.C_v.idxmin()]
zero = closed.loc[closed.C_v <= 0].iloc[0]
axes[0].text(.97, .62, f"closed: zero at $n={int(zero.lag)}$,\nmin ${low.C_v:.2f}$ at $n={int(low.lag)}$",
             transform=axes[0].transAxes, ha="right", va="top", fontsize=7, color=CIRCUIT["closed"])
axes[0].legend(fontsize=7.5, frameon=False, loc="upper right")
fig.tight_layout(pad=.3, w_pad=1.2)
fig.savefig(HERE / "assets/glide-autocorrelation-para.pdf")

# Numbers quoted on the slide.
def fmt(x):
    r = round(float(x), 2) + 0.0  # no "-0.00"
    return f"{r:.2f}".replace("-", "$-$")


values = {"GlideCohortGlides": f"{int(table.min_glides.iloc[0])}", "GlideMaxLag": f"{int(table.lag.max())}",
          "GlideFitA": f"{np.exp(intercept):.2f}", "GlideFitXi": f"{-1 / slope:.0f}",
          "GlideFitLo": f"{FIT_LAGS[0]}", "GlideFitHi": f"{FIT_LAGS[1]}"}
for task, prefix in (("open", "Open"), ("closed", "Closed")):
    d = table.loc[(table.task == task) & (table.lag >= 1)]
    low = d.loc[d.C_v.idxmin()]
    values[f"Glide{prefix}Flights"] = f"{int(d.flights.iloc[0]):,}"
    values[f"Glide{prefix}One"] = fmt(d.loc[d.lag == 1, "C_v"].iloc[0])
    values[f"Glide{prefix}Last"] = fmt(d.loc[d.lag == d.lag.max(), "C_v"].iloc[0])
    values[f"Glide{prefix}Min"] = fmt(low.C_v)
    values[f"Glide{prefix}MinLag"] = f"{int(low.lag)}"
values["GlideClosedZero"] = f"{int(table.loc[(table.task == 'closed') & (table.C_v <= 0), 'lag'].min())}"
lines = ["% Generated by render_glide_autocorrelation.py from glide-autocorrelation.csv."]
lines += [f"\\newcommand{{\\{k}}}{{{v}}}" for k, v in values.items()]
(HERE / "glide-autocorrelation-values.tex").write_text("\n".join(lines) + "\n")
print("\n".join(lines))
