"""Reproduce the sampling figures from the archived segmentation coverage tables.

Run with the repository Python environment. Only the small coverage tables are read.
Durations are sums of supported preprocessing-segment spans, excluding gaps.
"""
from pathlib import Path
import hashlib
import json
import pyarrow.parquet as pq

HERE = Path(__file__).resolve().parent
ARCHIVES = {
    "paragliders": Path("/Volumes/SSD_DISANTE/paragliders/ffvl_cfd_igc/derived/segmentation/vilpellet"),
    "hang_gliders": Path("/Volumes/SSD_DISANTE/hang_gliders/delta_cfd_igc/derived/segmentation/vilpellet"),
}
report = {"checked_on": "2026-10-07", "archive_snapshot": "2026-09-16", "denominator": "All preprocessing segments in each archived phase_coverage.parquet", "time_definition": "sum(t_end - t_start), excluding unsupported gaps", "flights_definition": "Distinct flight_id, retained if at least one segment qualifies", "groups": {}}
for name, directory in ARCHIVES.items():
    path = directory / "phase_coverage.parquet"
    d = pq.read_table(path).to_pandas()
    duration = d.t_end - d.t_start
    cadence = d.native_cadence_s < 1.2
    labelled = d.n_classified_fixes > 0
    total_flights = int(d.flight_id.nunique())
    total_fixes = int(d.n_native_fixes.sum())
    group = {
        "source": str(path), "sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
        "total_flights": total_flights, "total_fixes": total_fixes,
        "total_supported_seconds": float(duration.sum()),
    }
    for key, mask in [("cadence_eligible", cadence), ("classified", labelled)]:
        n = int(d.loc[mask, "flight_id"].nunique())
        fixes = int(d.loc[mask, "n_native_fixes"].sum())
        seconds = float(duration[mask].sum())
        group[key] = {"flights": n, "flight_percent": 100*n/total_flights, "fixes": fixes, "fix_percent": 100*fixes/total_fixes, "seconds": seconds, "time_percent": 100*seconds/duration.sum()}
    group["reason_fix_counts"] = {str(k): int(v) for k, v in d.groupby("status").n_native_fixes.sum().items()}
    assert int(d.n_classified_fixes.sum()) == group["classified"]["fixes"]
    report["groups"][name] = group

(HERE / "coverage-audit.json").write_text(json.dumps(report, indent=2) + "\n")
lines = ["% Generated by audit_coverage.py. Archived segmentation snapshot: 16 Sep 2026."]
for name, prefix in [("paragliders", "Para"), ("hang_gliders", "Hang")]:
    g = report["groups"][name]
    vals = {"TotalFlights": f'{g["total_flights"]:,}', "ClassFlights": f'{g["classified"]["flights"]:,}', "ClassFlightPct": f'{g["classified"]["flight_percent"]:.1f}', "ClassFixPct": f'{g["classified"]["fix_percent"]:.1f}', "ClassTimePct": f'{g["classified"]["time_percent"]:.1f}', "LostTimePct": f'{100-g["classified"]["time_percent"]:.1f}', "CadTimePct": f'{g["cadence_eligible"]["time_percent"]:.1f}', "CadFixPct": f'{g["cadence_eligible"]["fix_percent"]:.1f}', "CadFlightPct": f'{g["cadence_eligible"]["flight_percent"]:.1f}'}
    lines += [f"\\newcommand{{\\{prefix}{key}}}{{{value}}}" for key, value in vals.items()]
(HERE / "coverage-values.tex").write_text("\n".join(lines) + "\n")
print(json.dumps(report, indent=2))
